### ISSUE TITLE
custom css not working any more with versions 3.x

### ISSUE THREAD

**Issue by sebastianelsner** [zulip/zulip-desktop#807]
The following custom css is working with 2.3.82, but not with 3.0/3.1

```css
#private-container {
    max-height: 500px;
    min-height: 800px;
}

.zoom-in .show-more-topics, .zoom-in .zoom-in-hide, .zoom-out .zoom-out-hide, .zoomed-in .show-more-private-messages, .zoomed-out .zoom-out-hide {
    display: block !important;
}

```
The css will expand the height of the private messages section.

Tested on CentOS 7.5 with aforementioned Zulip Desktop versions. Zulip Server is 2.0.3.
